server:
  port: 8081

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:sqlserver://server-fiap-notes.database.windows.net:1433;database=dbFiapNotes;
    username: fiap
    password: roxo@2022
  azure:
    passwordless-enabled: true
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect

  cloud:
    azure:
      storage:
        blob:
          account-name: storagefiapnotes
          account-key: xCN9fp/nJXqcRCjTEc4xvQZjYmzvQcQzhMrTwaG9LDgG6cXl5Uhhn313Xg4Hg9ALlZLSsAW6uAvT+ASt7XUCbw==
          endpoint: DefaultEndpointsProtocol=https;AccountName=storagefiapnotes;AccountKey=xCN9fp/nJXqcRCjTEc4xvQZjYmzvQcQzhMrTwaG9LDgG6cXl5Uhhn313Xg4Hg9ALlZLSsAW6uAvT+ASt7XUCbw==;EndpointSuffix=core.windows.net

jwt:
  secret: f14ajdj646
  expireMinutes: 20
