server:
  port: 8081

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:h2:~/dbh2/fiap-notes;DB_CLOSE_ON_EXIT=FALSE
    username: fiap
    password: fiap
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: f14ajdj646
  expireMinutes: 20
azure:
  storage:
    account-name: storagefiapnotes
    account-key: xCN9fp/nJXqcRCjTEc4xvQZjYmzvQcQzhMrTwaG9LDgG6cXl5Uhhn313Xg4Hg9ALlZLSsAW6uAvT+ASt7XUCbw==
    blob-endpoint: https://storagefiapnotes.blob.core.windows.net

file:
  upload-dir: ./uploads